package com.web.webmapsoft.clientews;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 28-11-2015
//
//---------------------------------------------------



public interface NLIIServiceEvents
{
    public void Starting();
    public void Completed(NLIOperationResult result);
}
