package com.web.webmapsoft.clientews;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 28-11-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NLIZstPmDataSibtc extends AttributeContainer implements KvmSerializable
{

    
    public String CodBarras;
    
    public String NewCodBarras;
    
    public String NumSerie;
    
    public String Lote;
    
    public String CapaCloro;
    
    public String TaraReal;
    
    public String TipoRecipi;
    
    public String TaraImpresa;
    
    public String FchPruHidro;
    
    public String FchNextPrueba;
    
    public String TaraNueva;
    
    public String Estacion;

    public NLIZstPmDataSibtc ()
    {
    }

    public NLIZstPmDataSibtc (java.lang.Object paramObj,NLIExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("CodBarras"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.CodBarras = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.CodBarras = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("NewCodBarras"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.NewCodBarras = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.NewCodBarras = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("NumSerie"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.NumSerie = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.NumSerie = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("Lote"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.Lote = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.Lote = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("CapaCloro"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.CapaCloro = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.CapaCloro = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("TaraReal"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.TaraReal = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.TaraReal = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("TipoRecipi"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.TipoRecipi = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.TipoRecipi = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("TaraImpresa"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.TaraImpresa = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.TaraImpresa = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("FchPruHidro"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.FchPruHidro = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.FchPruHidro = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("FchNextPrueba"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.FchNextPrueba = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.FchNextPrueba = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("TaraNueva"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.TaraNueva = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.TaraNueva = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("Estacion"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.Estacion = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.Estacion = (String)obj;
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return CodBarras;
        }
        if(propertyIndex==1)
        {
            return NewCodBarras;
        }
        if(propertyIndex==2)
        {
            return NumSerie;
        }
        if(propertyIndex==3)
        {
            return Lote;
        }
        if(propertyIndex==4)
        {
            return CapaCloro;
        }
        if(propertyIndex==5)
        {
            return TaraReal;
        }
        if(propertyIndex==6)
        {
            return TipoRecipi;
        }
        if(propertyIndex==7)
        {
            return TaraImpresa;
        }
        if(propertyIndex==8)
        {
            return FchPruHidro;
        }
        if(propertyIndex==9)
        {
            return FchNextPrueba;
        }
        if(propertyIndex==10)
        {
            return TaraNueva;
        }
        if(propertyIndex==11)
        {
            return Estacion;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodBarras";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NewCodBarras";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NumSerie";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Lote";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CapaCloro";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TaraReal";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TipoRecipi";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TaraImpresa";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FchPruHidro";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FchNextPrueba";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TaraNueva";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Estacion";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
